### ISSUE TITLE
Launch checklist for GDC FO

### ISSUE THREAD

**Issue by bodhish** [pupilfirst/application-engine#4]
- [x] Deploy Application app in Digital Ocean
- [x] Rebrand website from `Bharath FieldOps` to `GDC FieldOps`
- [x] Onboarding Email template to be created. This should include details on what the students should do @aravindm4 
- [x] Update email from `bharat@pupilfirst.org` to `fieldops@gdc.network`
- [x] Deploy care on `http://care.coronasafe.live/`
- [x] Configure api to create users in care, (This needs a care production release) 
- [x] Delete last question about internship
- [x] Create certificate page
- [x] Webhook for course completion in lms
- [x] Webhook delivery endpoints 
- [x] Add Description to “Current District” - Type the name of district where you are currently residing and will be available to offer volunteer support in case of emergencies. 
- [x] Q2  Which stream are you studying in? - Capitalise M of medicine.
- [x] In Q3, Change This is a call for the Field Ops team to work towards managing the pandemic. This information regarding your health status is extremely important for your own safety.Your health and safety is an absolute PRIORITY!! Please answer this carefully to
"The district administration may allocate field/remote work based on your health status".
- [x] In Q4, Lets remove willingness to visit the field question.
- [x] Are you good at people facing roles?
Choose YES only if you have good communication skills and enjoy roles that require interaction with large number of people, have good patience and good interpersonal skills.
- [x] Are you good at technology facing roles?
Choose YES only if you are good at using computer software and the internet. You DON'T NEED TECHNICAL KNOWLEDGE OR SOFTWARE DEVELOPMENT SKILLS. All we are looking for is people who have good logical thinking and can learn to use software tools quickly.
- [x] Are you good at creative work?
Choose YES, if you are good at written communication/Visual communication as you may be of great value in content creation for training modules, websites, designing material for mass public campaigns, designing creatives for courses, documenting in written form or through photographs and videos.
- [x]  Q5. Change Hopeless, Bad, OK, Good and Excellent to
Weak
Manageable
Good
- [x] In question 6, we should add a line as description
"Your responses would determine the nature of work allocated to you during an emergency".
- [x] Check DOB :There was a bug in DOB. I'm 1984 born, but the application forced me to change DOB to 1992. (From Sanjay)
- [x] Application Status Message - Your application is short-listed for GDC Field Ops Fellowship Training. You can start accessing the courses by clicking on the  “Access Course” button below.
- [x] Add this to Application Status Page : We have sent an onboarding email with instruction on how to access the course. Please ensure to check your registered email and follow the instructions.
- [x] Replace “Continue Course” to “ Access Course” on Application Status Page
- [x] Update certificate page design 
- [x] Onboarding email - Update access end date  to May 22nd.
- [x] Onboarding email - General guidelines 4th point  - "After completion of the program, you will become part of the Emergency Reserve Cadre and can support efforts by district administration at times of any emergency. "
- [x] Add T&C to application - https://docs.google.com/document/d/1b7emi-E1QgbCsg9JzNAdkUOFwJRplohifVSwyKPkXQk/edit
